# Write your query or mutation here
mutation addBusiness($name: String!, $path: String!, $fram:String!){
    addBusiness(newDeploymentData:{
        name: $name,
        pathFolder: $path,
        framework: $fram
    }){
        uuid
        name
        pathFolder
        framework
    }
}
